services:
  app:
    build:
      context: .
    environment:
      - PORT=${APP_PORT:-4002}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST:-db}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - ${APP_PORT:-4002}:${APP_PORT:-4002}
    volumes:
      - .:/app

  db:
    image: mysql:8.0.37-debian
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    # command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
